### ISSUE TITLE
PHP Namespace bug

### ISSUE THREAD

**Issue by xskif** [wizza-smile/SublimeCodeIntel3#10]
I have namespace `common\components` in my project,
When i create new component, and typing `namespace common` tooltip offers me classes for `common` namespace, after typing `\` symbol tooltip forgot all about namespace and offers me `php` word and list of functions in alphabet order starts from `abs()`. After `compon` tooltip offers me something like this - `newt_component_add_callback(component, func_name, data)`

**Comment by wizza-smile** [comment]
i added a commit that should give you what you want. But you need to adjust PHP-syntax specific settings in Sublime. From "word_separators" you have to remove \\ so it will look something like this now:
```
{
    "word_separators": "./()\"'-:,.;<>~!@#%^&*|+=[]{}`~?",
}
```

Try and let me know!

**Comment by xskif** [comment]
Almost. Now it's offers me neighbour class names in namespace statement, but not the namespace parts, as i thought.

**Comment by wizza-smile** [comment]
``` it's will be perfect if plugin offers namespace by parts, like comm(offers common)\comp(offers components), etc. Or full namespace depend by file location.```

done!

``` I need to say that use statement works well before this commit and word_separators setting, now it's broken. =))```

it is doin so again!

```UPD3: why you can't test by yourself before push ? =))```

because I am fuckin lazy ;)

**Comment by xskif** [comment]
>done!

Almost =) after `namespace comm` it offers full list of class names what starts with `common` namespace =)
Also `namespace com` offers com_* functions and <command> tag.

After `\` all works fine.

**Comment by wizza-smile** [comment]
Yes, you are right. I changed that. Close the issue if satisfied!

**Comment by xskif** [comment]
I can't check that correctly, because after last pull live mode is broke.

If i press ctrl+shift+space all works fine. But where is live mode ?

**Comment by xskif** [comment]
Now all works fine. Thank you for work.
