### ISSUE TITLE
Tooltip blinking

### ISSUE THREAD

**Issue by xskif** [wizza-smile/SublimeCodeIntel3#11]
- When i start typing some method name, tooltip blinking after each letter.
- When i mistyped with object method name, tooltip still blinking, but hiding after each letter, if another object in the same file have similar method name, and current object doesn't. E.g. i have 2 models (e.g. first and second) with `load` method, but only one (e.g. first) have `save` method, so if i starts typing `$secondModel->sa` tooltip shows me `save()` completion and hiding immediately.
The same problem if i have `$this->someAwesomeMethod` and starts typing `$myModel->someAw`.

**Comment by wizza-smile** [comment]
please provide me with full php files to state your case. Its a little bit difficult to follow by description only!

thanx for your help !

**Comment by xskif** [comment]
It looks like plugin shows me tooltip with most similar method/function/property name, then suddenly realizes that this method/function/property doesn't belongs to this object, and hide tooltip.

When method present, it looks like any letter triggers show/hide event.

If it's not enough, i will try to upload some gist-file for easy test that error tomorrow.

**Comment by wizza-smile** [comment]
that would be awesome!

**Comment by wizza-smile** [comment]
Try again, it will be working now!

**Comment by xskif** [comment]
I need live mode to check that. In manual mode all works fine.

**Comment by wizza-smile** [comment]
i missed a line in the last commit. please try again!

**Comment by xskif** [comment]
Looks perfect.
