### ISSUE TITLE
Request standard function arguments hint (new version override PHP Complements Kit)

### ISSUE THREAD

**Issue by ptcong** [wizza-smile/SublimeCodeIntel3#2]
Hi, @wizza-smile 
The new version overrides PHP Completions Kit  (PCK) function arguments suggestion.
Eg: when i type `substr` and choose *standard function* of PCK suggestion, it give me

 `substr(string[, start, length)` then i will easy to fill how many arguments  i want by TAB -> fill.

Now with the version it only give me `substr()`. 

Is there anyway/setting to tell SublimeCodeIntel give me arguments hint ?

Sometimes i don't remember which is argument first and which is argument seconds of some functions like `stripos`, so the feature is helpful with me, but now it was overrided by the new version.

Could you add the feature to next version ?

**Comment by wizza-smile** [comment]
yes, you have to activate it by keyCommand.

my personal keybinding for this is:

{ "keys": ["shift+ctrl+space"], "command": "code_intel_auto_complete" }

now when your cursor is inside the brackets of a function and you press shift+ctrl+space,
a description of the function and parameters appears.

for build-in functions this will only happen, if you properly configured the following setting, as this will help CodeIntel to find the proper *.CIX file for your PHP-version: 

{
    "codeintel_settings": {
        "codeintel_language_settings": {
            "PHP": {
                "php": "/path/to/a/php-interpereter-exec"
            }
        }
    }



 Also: if in the *.sublime-settings file if you set

"codeintel_snippets": true

you can prefill function arguments by pressing TAB after you called the keyCommand described above!

**Comment by ptcong** [comment]
Amazing!!
It works, thank you @wizza-smile :+1: 
One more thing, now i see have 2 projects, your and https://github.com/SublimeCodeIntel/SublimeCodeIntel
What's project  i should watch ? and who will develop next versions of the plugin ?

**Comment by wizza-smile** [comment]
If you love fresh and crisp completions for ST3, you should definitely watch and use SublimeCodeIntel3!
