### ISSUE TITLE
sublime auto complete failed

### ISSUE THREAD

**Issue by lzyun** [wizza-smile/SublimeCodeIntel3#4]
When I installed SublimeCodeIntel3, the original sublime auto complete could not popup immediately. 

OS X 10.10
ST3 build3065
installed SublimeCodeIntel through the download zip file

**Comment by wizza-smile** [comment]
the default auto_complete setting from sublime gets disabled if the plugin is enabled for the language you are using. so this is by design. SublimeCodeIntel3 aims to replace sublime completions as good as possible. it would be extremly helpful if could share what you are missing the most in your completions, so that it can be added!
what language are you using?

**Comment by lzyun** [comment]
I wrote on python, but it seems that did not scan for the file in the project, so it cannot pop up with the exist parameter in the project.
I tried to add setting in the SublimeCodeIntel.sublime - user setting

"codeintel_config": {
        "Python": {
            "codeintel_scan_files_in_project": true,
        },
    }

**Comment by wizza-smile** [comment]
The setting you are looking for is no longer named "codeintel_config", it is now "codeintel_language_settings".
Please have close look at the 'Configuring' section in the readme.rst and also at the default *.sublime-settings file, that gets delivered with the plugin!

You might also want to add an interpreter for Python in the settings, to get completions for you site-packages!

Cheers

**Comment by lzyun** [comment]
hi,
I tried to edit my setting file with bellow
I though it could be the problem from "codeintel_word_completions": "buffer",


    def main():
        test1 = "12345"
        test

    if __name__ == '__main__':
        main()

But I still cannot get the word completion when i type test it could not show the test1 in the popup
    
     {
        "codeintel_language_settings": {
            "Python": {
                "python":"/usr/bin/python27",
                "codeintel_scan_files_in_project": true,
                "codeintel_scan_extra_dir": ["/usr/local/lib/python2.7/site-packages"],
                "codeintel_word_completions": "all",
                "codeintel_snippets": true,
                "codeintel_tooltips": "popup",
            },
         }
    }

**Comment by wizza-smile** [comment]
anything going on in the sublime console?

**Comment by lzyun** [comment]
just show the `processing 'Python': please wait...` for a long time and appear what i want

**Comment by spectacles** [comment]
That would be your status bar.  sublime console is under View > Show Console!

**Comment by lzyun** [comment]
Yes, I open the sublime console through <code>control + `<code>
And I got 
    + Info: processing `Python': please wait...
    processing `Python': please wait...
    Could not import subprocess32 module, falling back to subprocess module

**Comment by wizza-smile** [comment]
looks pretty good from here! SublimeCodeIntel3 will never actually AUTO-complete, you have to press the Tab-key to execute completion!

**Comment by lzyun** [comment]
Actually it appear the popup really slow. I will keep looking and find the reason, thanks.

**Comment by wizza-smile** [comment]
Do you still have this problem? Is it slow only after Sublime startup, or does it stay slow all the time?

**Comment by lzyun** [comment]
It just stay slow all the time.
And the function what I import is showing more fast then the code parameter I typed in the file.
I still can not figure out what's the problem.

**Comment by wizza-smile** [comment]
if I look again at the image you provided I can see it is loading plugin "Sublimecodeintel.ordereddict" which is not part of SublimeCodeIntel3. This plugin is only part of SublimeCodeIntel v 2.1.1

I can only support you if you are using SublimeCodeIntel3!

**Comment by lzyun** [comment]
I remove the v2.1.1 and put the SublimeCodeIntel3 again.
Still got the same problem, stay slow all the time about 5 seconds or more.




![screen shot 2015-01-19 at 5 51 46 pm](https://cloud.githubusercontent.com/assets/6794886/5798650/79564510-a004-11e4-9902-ad6f28e0e98f.png)

**Comment by wizza-smile** [comment]
can you please configure a new project?!
In this project set a "codeintel_database_dir" specifically for this project. Make sure it gets created.
Make sure there is only this one file in that project!

Now try again! Is the problem still occurring?

**Comment by lzyun** [comment]
setting with this
![screen shot 2015-01-19 at 7 48 13 pm](https://cloud.githubusercontent.com/assets/6794886/5800003/24d97a06-a014-11e4-8b34-153f21bb351e.png)

but seems the same. they stay slow all the time.

![screen shot 2015-01-19 at 7 44 57 pm](https://cloud.githubusercontent.com/assets/6794886/5799969/baa46c86-a013-11e4-8de5-d5a00afc9dda.png)

something strange in the console like 

![screen shot 2015-01-19 at 7 50 46 pm](https://cloud.githubusercontent.com/assets/6794886/5800026/8d907392-a014-11e4-927c-dd1bc45f2159.png)

and the privilege of the file is  like 
![screen shot 2015-01-19 at 7 52 53 pm](https://cloud.githubusercontent.com/assets/6794886/5800044/cbe517f6-a014-11e4-8917-6c4e8ef7097e.png)

**Comment by wizza-smile** [comment]
There are a lot of things wrong in your setup!

You have a wrong version of SublimeCodeIntel.py. Please re-download the zip and install again. Make really sure you remove all other versions of SublimeCodeIntel!

Also: "codeintel_database_dir" defines a directory in which the database will be created. It cannot be overridden per language also, so you you have to put it outside of "codeintel_language_settings"! And lastly: the setting doesnt take an array, so you have to remove the [ ] brackets around it!

**Comment by lzyun** [comment]
Sorry about my negligence on the setup file. I tried to remove all the document about Sublime text and reinstall SublimeCodeIntel3 and meet the same problem. I try other auto completion(jedi) after installed and everything work fine. I think it may the environment problem of my computer. 
Whatever, thanks for your help.
sincerely,

**Comment by wizza-smile** [comment]
so painful to loose my customer :stuck_out_tongue_winking_eye:
