### ISSUE TITLE
`class_` have no hints and can i change the delay time of autocomplete ?

### ISSUE THREAD

**Issue by ptcong** [wizza-smile/SublimeCodeIntel3#6]
Hi @wizza-smile,
When i type `class_` or `class_e` and request autocomplete, no results show. I must delete `_e` and wait 1-2 seconds to see the suggestions.

Is there an anyway to change the delay ?
My typing speed is quite high, so i don't want to wait 1-2 seconds to see the hints.

**Comment by wizza-smile** [comment]
I'll describe how it is with me!
The first after Sublime startup or after project change, the completions will take 1-2 seconds. This is because the codeIntel-machine is soaking its caches.
After the completions appeared once, it will boil down to ~300ms, which is fast enough for me (in my view completions, as programming, is NOT about speed, but about comfort!!!)

Also: "class_e" is totally working for me, so something else might be malconfigured in your setup?

all the best!

**Comment by wizza-smile** [comment]
hey @ptcong !
Exciting news! I can confirm the issue with ```class_```. No completions are showing, UNLESS you have some brackets around it. So ```if (class_)``` will actually show completions (please confirm!)

I checked on SublimeCodeIntel v 2.0.6: the same issue there! I could not find any other case where completions are not working, so this could be some strange Sublime bug.

if you type ```clas_e``` though, completions will always show. so its the combination of "ss_" that makes Sublime stumble. For whatever reason!

**Comment by ptcong** [comment]
Yes, `if(class_` still works, but if no wrapped in the `if`, i think ST or CodeIntel think i'm defining a class ?
For delay time to show suggestions, i think it is 300 ms (CodeIntel not reindex my project at the time). But 300ms is slower than i type full function or class name :D even when i request suggestion, it still delay a time. 
I saw PHP Storm or DW suggest is faster, could you improve its speed or give users an options that decide the delay time ?

**Comment by wizza-smile** [comment]
this is exactly the same issue as this one just in PHP instead of Python:

https://github.com/srusskih/SublimeJEDI/issues/150

You have to override Sublimes default "Completion Rules.tmPreferences" in PHP.sublime-package. 
By default Sublime cancels completions on words like "class" or "function"!

**Comment by ptcong** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>scope</key>
    <string>source.php</string>
    <key>settings</key>
    <dict>
        <key>cancelCompletion</key>
        <string>^(.*\b(and|or)$)|(\s*(pass|return|and|or)$)</string>
    </dict>
</dict>
</plist>
```
I just created the *Completion Rules.tmPreferences* file and put to *Packages/PHP/Completion Rules.tmPreferences*  then type `class_e` or `class_` it not show any suggestions. But only `class` then request suggestions, it works (i think you have made it).

nothing changed ??

**Comment by wizza-smile** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>scope</key>
    <string>source.php</string>
    <key>settings</key>
    <dict>
        <key>cancelCompletion</key>
        <string>^\s*(\}?\s*(else|do|try)|(function)\s*[a-zA-Z_0-9]+)$</string>
    </dict>
</dict>
</plist>
````

That is the file that is working for me. Also in the SublimeText Folder I had to delete the ```cache```directory and the file ```Session.sublime_session``` from the ```local``` directory.

**Comment by wizza-smile** [comment]
hey @ptcong! There is a new version out! Completions are super fast now! Please feedback!

**Comment by ptcong** [comment]
Amazing!!! 

Thank you very much @wizza-smile.
