### ISSUE TITLE
Request support __construct(), __destruct(), ... magic methods..

### ISSUE THREAD

**Issue by ptcong** [wizza-smile/SublimeCodeIntel3#7]
Hi @wizza-smile ,
I'm working in PHP, general the plugins is good, but sometimes when i going to create __construct, __destruct, __clone ...etc the plugins don't suggest the keywords.

Could you consider to support this ?

**Comment by wizza-smile** [comment]
okay, I implemented this, so you can download latest version!

if you now type in a class (example):
```public function __c```
completions will appear.

You need to type at least 3 chars!

feedback please!

**Comment by ptcong** [comment]
Ok, got it thank you very much.

Could you create a package on packagecontrol.io then support auto update if have new version, users don't need update by manual ?

One more thing, snippet feature don't insert optional argument, sometimes i need the arguments to entry faster. Could you add new options for this, and one option for automatic insert arguments when user enter to a function suggestions ?

**Comment by wizza-smile** [comment]
please open a feature request!
