### ISSUE TITLE
Request auto update and auto insert arguments option

### ISSUE THREAD

**Issue by ptcong** [wizza-smile/SublimeCodeIntel3#8]
Could you create a package on packagecontrol.io then support auto update if have new version, users don't need update by manual ?

One more thing, snippet feature don't insert optional argument, sometimes i need the arguments to entry faster. Could you add new options for this, and one option for automatic insert arguments when user enter to a function suggestions ?

**Comment by wizza-smile** [comment]
@ptcong sorry, but I don't really understand what exactly you are looking for. Can you please elaborate?!

**Comment by ptcong** [comment]
sorry, my english is not good.
I request 2 features.
- Allows ST3 automatic update newest version of the plugin if have. (you should create a package in packagecontrol.io)
- Option that tell CodeIntel3 insert arguments when i choose a function in suggestion list - don't need ctrl +shift + space to get argument hints.

**Comment by xskif** [comment]
+1 for this issue.

**Comment by wizza-smile** [comment]
Hey people, 
I renamed the project and moved it here:
https://github.com/spectacles/CodeComplice

The tooltips are now included stronger.
You can add even optional arguments by typing "," and pressing TAB-key after the last mandatory argument.

Let me know if you like it!

**Comment by xskif** [comment]
Is project will be distributed by Package Control (https://packagecontrol.io/)?

**Comment by wizza-smile** [comment]
yes it is available. "CodeComplice"

**Comment by wizza-smile** [comment]
hey @ptcong, please also check out "CodeComplice" on PackageControl. I need feedback on tooltips optional arguments! thanx!!!

**Comment by ptcong** [comment]
@wizza-smile great man !
Thank you very much :+1:

**Comment by xskif** [comment]
so i can delete SublimeCodeIntel3 package and install CodeComplice instead. right?

**Comment by ptcong** [comment]
@xskif right, i just done and use all defaults of configurations. It's nice!

**Comment by xskif** [comment]
@ptcong ok, thanks.
